apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: react-frontend
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://github.com/shani768/kubernates-static-website-deployment.git'
    targetRevision: main
    path: k8s/manifest
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
