on:
  push:
    branches:
      - main
    paths:
      - 'frontend/**'   # Trigger only if files inside frontend/ change

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      # Login to Docker Hub
      - name: Docker Login
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}

      # Build Docker Image
      - name: Build Docker Image
        run: |
          cd frontend
          IMAGE_NAME=shani000786/static-react-website
          UNIQUE_TAG=$(echo $GITHUB_SHA | cut -c1-8)
          docker build -t $IMAGE_NAME:$UNIQUE_TAG -t $IMAGE_NAME:latest .

      # Push Docker Image
      - name: Push Docker Image
        run: |
          IMAGE_NAME=shani000786/static-react-website
          UNIQUE_TAG=$(echo $GITHUB_SHA | cut -c1-8)
          docker push $IMAGE_NAME:$UNIQUE_TAG
          docker push $IMAGE_NAME:latest
