name: Frontend CI/CD

on:
  push:
    branches:
      - main
    paths:
      - 'frontend/**'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Docker Login
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}

      - name: Build and Push Docker Image with SHA
        run: |
          IMAGE_NAME=shani000786/static-react-website
          UNIQUE_TAG=$(echo $GITHUB_SHA | cut -c1-8)
          cd frontend
          docker build -t $IMAGE_NAME:$UNIQUE_TAG -t $IMAGE_NAME:latest .
          docker push $IMAGE_NAME:$UNIQUE_TAG
          docker push $IMAGE_NAME:latest
          echo "IMAGE_TAG=$UNIQUE_TAG" >> $GITHUB_ENV

      - name: Update Kubernetes Deployment Image Tag
        run: |
          sed -i "s|image: shani000786/static-react-website:.*|image: shani000786/static-react-website:${IMAGE_TAG}|g" k8s/manifest/frontend.yaml

      - name: Commit and Push Updated YAML
        run: |
          git config --global user.name "shani768"
          git config --global user.email "zeeshantahir779@gmail.com"
          git add k8s/manifest/frontend.yaml
          git commit -m "Update frontend image tag to ${IMAGE_TAG}"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
